### ISSUE TITLE
Hybrid workshop

### ISSUE THREAD

**Issue by BenEmdon** [BenEmdon/Swift-iOS-Workshop#1]
This workshop could be improved if we spend _Swift learning time_ in a Swift Playground and _app developing time_ in Xcode. The Swift Playground simulator is no substitution for the regular Xcode simulator because of:
* different simulator screen sizes and layout
* text input
* hardware specific things (e.g. networking, gps, etc...)

Other takeaways from the workshop:
* Programatic layout is not easy for beginners.
* If you want to introduce Autolayout, allocate more time than you think you need.

☝️ These points suggest that we teach storyboards to beginners, and programatic view management to intermediates/advanced learners.

**Comment by riconaranjo** [comment]
Some other thoughts: 

- Make the workshop **more interactive** by having participants write Swift code in Playgrounds [active vs passive learning]
- Given we only had 50 min, it **went pretty well**. The current format is better suited for a 90 min format.

Overall very happy with the turnout, the participants enjoyed it and showed interest in attending more workshops in the future. 🙂
